### ISSUE TITLE
Get Recent Late Contributions by Date: not difference in http response with different year parameter input

### ISSUE THREAD

**Issue by DavytJ** [propublica/campaign-finance-api-docs#5]
I understand that year parameter accept four-digit year from 2001-2018. But there are not difference in response if we put year = 2000 or year = 2002. Is it possible to expect different responses?

**Comment by dwillis** [comment]
@DavytJ Can you give me the example urls you're trying?

**Comment by DavytJ** [comment]
https://api.propublica.org/campaign-finance/v1/{cycle}/contributions/48hour/{year}/{month}/{day}
https://api.propublica.org/campaign-finance/v1/2000/contributions/48hour/2000/09/07.json
https://api.propublica.org/campaign-finance/v1/2016/contributions/48hour/2002/09/07.json
https://api.propublica.org/campaign-finance/v1/2002/contributions/48hour/2002/09/07.json

return:

$status
[1] "OK"

$copyright
[1] "Copyright (c) 2018 ProPublica Inc. All Rights Reserved."

$base_uri
[1] "https://api.propublica.org/campaign-finance/v1/2016/"

$cycle
[1] 2016

$offset
NULL

$results
list()

$callback
NULL

**Comment by dwillis** [comment]
@DavytJ Ok, thanks. It seems like the issue here is that the responses are based only on the year/month/day variables - that it pays no attention to the cycle attribute. But a more important point is that the API docs say that the 48 hour contribution responses are for 2010 forward, so a 2000 or 2002 request will not result in any data. I will fix the response so that the cycle and the year are dependent.

**Comment by dwillis** [comment]
These fixes have been deployed.

**Comment by DavytJ** [comment]
Ok, I see. Only check the api-docs:
https://projects.propublica.org/api-docs/campaign-finance/candidates/#get-recent-late-contributions-by-date

**Comment by dwillis** [comment]
Fixed now.
